### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by antalaszek** [gmjosack/getotp#1]
After running command 
```pip install getotp```

i get 

```
Collecting getotp
  Using cached getotp-0.0.3.tar.gz (3.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-fywrbmk9/getotp_4cc93921e66147bca3d845829a2794ba/setup.py", line 6, in <module>
          execfile('getotp/version.py')
      NameError: name 'execfile' is not defined
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Fedora, pip 22.1.2, python 3.10

**Comment by gmjosack** [comment]
Version 0.1.0 is now on PyPI and is Python 3 compatible.
